FROM python:3.10-slim

WORKDIR /app

COPY requirements-streamlit.txt .
RUN pip install --no-cache-dir -r requirements-streamlit.txt

COPY streamlit_app.py .
COPY pages ./pages
COPY streamlit_dashboard ./streamlit_dashboard
COPY include ./include

EXPOSE 8501

CMD ["streamlit", "run", "streamlit_app.py", "--server.address=0.0.0.0", "--server.port=8501"]
